---
- name: Get env variables
  hosts: all
  tasks:
    - name: Get environment variables
      ansible.builtin.command: printenv
      register: env_vars

    - name: Display environment variables
      ansible.builtin.debug:
        var: env_vars.stdout_lines