- name: Copy private key to worker node
  hosts: all
  become: true
  tasks:
    - name: Copy private key
      ansible.builtin.copy:
        src: /home/ec2-user/.ssh/authorized_keys
        dest: /home/ec2-user/.ssh/id_rsa
        owner: ec2-user
        group: ec2-user
        mode: '0600'
