---
- name: Confiugre the playbook
  hosts: all
  tasks:
    - name: Ensure the playbook is running
      ping:
    - name: Print a message
      debug:
        msg: "Playbook is configured and running successfully"
    - name: create file
      ansible.builtin.command:
        cmd: echo "this file is created by ansible playbook" > /tmp/ansible_test_file.txt
      become: true
      register: create_file
    - name: debug create file result
      ansible.builtin.debug:
        var: create_file
    - name: Ensure the file exists
      ansible.builtin.stat:
        path: /tmp/ansible_test_file.txt
      register: file_stat
    - name: debug file stat
      ansible.builtin.debug:
        var: file_stat
    - name: Install a package 
      ansible.builtin.yum:
        name:
          - vim
          - git
          - wget 
        state: present
      become: true
      register: install_vim
    - name: debug install result
      ansible.builtin.debug:
        var: install_vim